// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.Data;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251116091046_AddedMeetingModel")]
    partial class AddedMeetingModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("api.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Web Dev"
                        });
                });

            modelBuilder.Entity("api.Models.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("LobbyId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LobbyId");

                    b.HasIndex("UserId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("api.Models.Lobby", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RepositoryUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Lobbies");
                });

            modelBuilder.Entity("api.Models.LobbyMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("LobbyId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("UserSelectionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LobbyId");

                    b.HasIndex("UserId");

                    b.ToTable("LobbyMembers");
                });

            modelBuilder.Entity("api.Models.Meetings.Meeting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MeetingProposalId")
                        .HasColumnType("int");

                    b.Property<string>("TeamsMeetingLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MeetingProposalId")
                        .IsUnique();

                    b.ToTable("Meetings");
                });

            modelBuilder.Entity("api.Models.Meetings.MeetingProposal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("LobbyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("MeetingTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LobbyId");

                    b.HasIndex("UserId");

                    b.ToTable("MeetingProposals");
                });

            modelBuilder.Entity("api.Models.Meetings.MeetingVote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MeetingProposalId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<bool>("Vote")
                        .HasColumnType("bit");

                    b.Property<DateTime>("VotedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MeetingProposalId");

                    b.HasIndex("UserId");

                    b.ToTable("MeetingVotes");
                });

            modelBuilder.Entity("api.Models.ProgrammingLanguage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("ProgrammingLanguages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "JavaScript",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Python",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Python",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 4,
                            Name = "Standard",
                            RoleId = 4
                        });
                });

            modelBuilder.Entity("api.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Name = "Frontend"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Name = "Backend"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Name = "QA"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Name = "PM"
                        });
                });

            modelBuilder.Entity("api.Models.Tasks.TaskDefinitions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TaskDefinitions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 1,
                            Description = "",
                            IsCompleted = false,
                            Name = "Book meeting"
                        },
                        new
                        {
                            Id = 2,
                            Category = 1,
                            Description = "",
                            IsCompleted = false,
                            Name = "Attend your scheduled team meeting"
                        },
                        new
                        {
                            Id = 3,
                            Category = 1,
                            Description = "",
                            IsCompleted = false,
                            Name = "Break down the tasks"
                        },
                        new
                        {
                            Id = 4,
                            Category = 0,
                            Description = "",
                            IsCompleted = false,
                            Name = "Visit github repository"
                        },
                        new
                        {
                            Id = 5,
                            Category = 0,
                            Description = "",
                            IsCompleted = false,
                            Name = "Start coding"
                        });
                });

            modelBuilder.Entity("api.Models.Tasks.TeamTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeamTaskProgressId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamTaskProgressId");

                    b.ToTable("TeamTasks");
                });

            modelBuilder.Entity("api.Models.Tasks.TeamTaskProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LobbyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LobbyId")
                        .IsUnique();

                    b.ToTable("TeamTaskProgresses");
                });

            modelBuilder.Entity("api.Models.Tasks.UserTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserTaskProgressId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserTaskProgressId");

                    b.ToTable("UserTasks");
                });

            modelBuilder.Entity("api.Models.Tasks.UserTaskProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LobbyMemberId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LobbyMemberId")
                        .IsUnique();

                    b.ToTable("UserTaskProgresses");
                });

            modelBuilder.Entity("api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("GithubToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("api.Models.UserLanguage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProgrammingLanguageId")
                        .HasColumnType("int");

                    b.Property<int>("UserSelectionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProgrammingLanguageId");

                    b.HasIndex("UserSelectionId");

                    b.ToTable("UserLanguages");
                });

            modelBuilder.Entity("api.Models.UserSelection", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSelections");
                });

            modelBuilder.Entity("api.Models.ChatMessage", b =>
                {
                    b.HasOne("api.Models.Lobby", "Lobby")
                        .WithMany()
                        .HasForeignKey("LobbyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lobby");

                    b.Navigation("User");
                });

            modelBuilder.Entity("api.Models.LobbyMember", b =>
                {
                    b.HasOne("api.Models.Lobby", "Lobby")
                        .WithMany()
                        .HasForeignKey("LobbyId");

                    b.HasOne("api.Models.User", "User")
                        .WithMany("LobbbyQueues")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Lobby");

                    b.Navigation("User");
                });

            modelBuilder.Entity("api.Models.Meetings.Meeting", b =>
                {
                    b.HasOne("api.Models.Meetings.MeetingProposal", "MeetingProposal")
                        .WithOne("Meeting")
                        .HasForeignKey("api.Models.Meetings.Meeting", "MeetingProposalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MeetingProposal");
                });

            modelBuilder.Entity("api.Models.Meetings.MeetingProposal", b =>
                {
                    b.HasOne("api.Models.Lobby", "Lobby")
                        .WithMany()
                        .HasForeignKey("LobbyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lobby");

                    b.Navigation("User");
                });

            modelBuilder.Entity("api.Models.Meetings.MeetingVote", b =>
                {
                    b.HasOne("api.Models.Meetings.MeetingProposal", "MeetingProposal")
                        .WithMany("Votes")
                        .HasForeignKey("MeetingProposalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("MeetingProposal");

                    b.Navigation("User");
                });

            modelBuilder.Entity("api.Models.ProgrammingLanguage", b =>
                {
                    b.HasOne("api.Models.Role", "Role")
                        .WithMany("ProgrammingLanguages")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("api.Models.Role", b =>
                {
                    b.HasOne("api.Models.Category", "Category")
                        .WithMany("Roles")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("api.Models.Tasks.TeamTask", b =>
                {
                    b.HasOne("api.Models.Tasks.TeamTaskProgress", "TeamTaskProgress")
                        .WithMany("TeamTasks")
                        .HasForeignKey("TeamTaskProgressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TeamTaskProgress");
                });

            modelBuilder.Entity("api.Models.Tasks.TeamTaskProgress", b =>
                {
                    b.HasOne("api.Models.Lobby", "Lobby")
                        .WithOne("TeamTaskProgress")
                        .HasForeignKey("api.Models.Tasks.TeamTaskProgress", "LobbyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lobby");
                });

            modelBuilder.Entity("api.Models.Tasks.UserTask", b =>
                {
                    b.HasOne("api.Models.Tasks.UserTaskProgress", "UserTaskProgress")
                        .WithMany("UserTasks")
                        .HasForeignKey("UserTaskProgressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserTaskProgress");
                });

            modelBuilder.Entity("api.Models.Tasks.UserTaskProgress", b =>
                {
                    b.HasOne("api.Models.LobbyMember", "LobbyMember")
                        .WithOne("UserTaskProgress")
                        .HasForeignKey("api.Models.Tasks.UserTaskProgress", "LobbyMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LobbyMember");
                });

            modelBuilder.Entity("api.Models.UserLanguage", b =>
                {
                    b.HasOne("api.Models.ProgrammingLanguage", "ProgrammingLanguage")
                        .WithMany("UserLanguages")
                        .HasForeignKey("ProgrammingLanguageId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("api.Models.UserSelection", "UserSelection")
                        .WithMany("UserLanguages")
                        .HasForeignKey("UserSelectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProgrammingLanguage");

                    b.Navigation("UserSelection");
                });

            modelBuilder.Entity("api.Models.UserSelection", b =>
                {
                    b.HasOne("api.Models.Category", "Category")
                        .WithMany("UserSelections")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("api.Models.LobbyMember", "LobbyQueue")
                        .WithOne("UserSelection")
                        .HasForeignKey("api.Models.UserSelection", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Models.Role", "Role")
                        .WithMany("UserSelections")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("api.Models.User", "User")
                        .WithMany("UserSelections")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("LobbyQueue");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("api.Models.Category", b =>
                {
                    b.Navigation("Roles");

                    b.Navigation("UserSelections");
                });

            modelBuilder.Entity("api.Models.Lobby", b =>
                {
                    b.Navigation("TeamTaskProgress")
                        .IsRequired();
                });

            modelBuilder.Entity("api.Models.LobbyMember", b =>
                {
                    b.Navigation("UserSelection")
                        .IsRequired();

                    b.Navigation("UserTaskProgress")
                        .IsRequired();
                });

            modelBuilder.Entity("api.Models.Meetings.MeetingProposal", b =>
                {
                    b.Navigation("Meeting")
                        .IsRequired();

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("api.Models.ProgrammingLanguage", b =>
                {
                    b.Navigation("UserLanguages");
                });

            modelBuilder.Entity("api.Models.Role", b =>
                {
                    b.Navigation("ProgrammingLanguages");

                    b.Navigation("UserSelections");
                });

            modelBuilder.Entity("api.Models.Tasks.TeamTaskProgress", b =>
                {
                    b.Navigation("TeamTasks");
                });

            modelBuilder.Entity("api.Models.Tasks.UserTaskProgress", b =>
                {
                    b.Navigation("UserTasks");
                });

            modelBuilder.Entity("api.Models.User", b =>
                {
                    b.Navigation("LobbbyQueues");

                    b.Navigation("UserSelections");
                });

            modelBuilder.Entity("api.Models.UserSelection", b =>
                {
                    b.Navigation("UserLanguages");
                });
#pragma warning restore 612, 618
        }
    }
}
